server:
  port: 8080
  ssl:
    key-store: ${SSL_KEYSTORE_DIR}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    client-auth: ${SSL_CLIENT_AUTH}
    enabled: ${SSL_ENABLED}
    trust-store: ${SSL_TRUSTSTORE_DIR}
    trust-store-password: ${SSL_TRUSTSTORE_PASSWORD}
  error:
    whitelabel:
      enabled: false
#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true


network:
  appelli:
    host: https://appelli:8080
  prenotazioni:
    host: https://prenotazioni:8080